jobs:
- job: fluentui_icons_apple_publish_nuget
  pool:
    vmImage: 'macos-10.15'
  displayName: FluentUI Icons Apple Publish NuGet
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
  
  steps:
  # Select proper XCode version
  - template: apple-xcode-select.yml
      
  # Zip our build output. It's important to zip here to preserve symlinks
  - bash: 'scripts/prepare_for_nuget_pack.sh'
    displayName: 'Zip build output for NuGet'

  # generate the sanitizedBuildNumber environment variable
  - bash: 'scripts/generate_build_number.sh'
    displayName: 'Generate Build Number'

  # pack the nuspec
  - task: NuGetCommand@2
    displayName: 'NuGet pack'
    inputs:
      command: pack
      packagesToPack: 'FluentUISystemIcons.nuspec'
      buildProperties: buildNumber=$(sanitizedBuildNumber);commitId=$(Build.SourceVersion);repoUri=$(Build.Repository.Uri)

  # push the package package
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/Microsoft.FluentUI.System.Icons.Apple.*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: Office
